// Author: Alex Tappin
// alexander.tappin@oit.edu
#pragma once
//**************************************
// lex.h
//
// Defines global symbols used the the flex generated lexer and 
// bison generated parser.
//
// Author: Alex Tappin, Anthony Nguyen
// 

// parse function generated by bison
#pragma once

#include "cSymbolTable.h"
#include "cSymbol.h"
#include "cAstNode.h"
#include "blockNode.h"
#include "printNode.h"
#include "exprNode.h"
#include "stmtsNode.h"
#include "langparse.h"

extern char *yytext;
extern int yylineno;
extern cSymbolTable *symbolTableRoot;
extern FILE *yyin;          // input file for lexer
extern int yyparse();
extern int yylex();
