#pragma once
//**************************************
// lex.h
//
// Defines global symbols used the the flex generated lexer and 
// bison generated parser.
//
// Author: Anthony Nguyen   anthony.nguyen@oit.edu
//

// parse function generated by bison
int yyparse();

// lexer function generated by flex
int yylex();

extern char *yytext;        // text of the current token
extern int yylineno;        // line number of current token
extern FILE *yyin;          // input file for lexer
extern cSymbol yylval;